import fs from "node:fs";
import path from "node:path";
import { atomicWrite, getRouboDir } from "./state.js";

/**
 * The notifier program core ships for the `spawned-notifier` notification
 * wiring (issue #698, AP-FR-013).
 *
 * An agent declaring `capabilities.notification.kind === "spawned-notifier"`
 * cannot POST to core itself: it spawns a configured program when its declared
 * event fires, passing that program's configured arguments plus the event JSON
 * as one final argument. Core therefore has to supply the program, and the
 * program has to be agent-generic: nothing here knows or cares which agent
 * spawned it, so the name carries no agent vocabulary.
 *
 * Two constraints shape it.
 *
 * The endpoint URL is baked in at write time rather than read from the
 * environment, because ROUBO_PORT is deliberately stripped from every bench
 * child env (HOST_INTERNAL_ENV_KEYS in terminal.ts): core tells the agent the
 * port, the agent never inherits it. The notifier is a child of the agent, so it
 * inherits the same stripped env and has no runtime way to learn the port. The
 * same reasoning already bakes the hook URL into the Claude Code settings write.
 *
 * It is a POSIX `sh` script rather than a Node entry point, because the packaged
 * app targets macOS and Linux only and a Node program would have to be a second
 * bundle output beside the single-entry server bundle. `sh` plus `curl` is
 * present on both targets and starts in milliseconds.
 */

/**
 * The program name a plugin writes into its carrier argv. Fixed, never
 * interpolated from plugin input, and deliberately agent-neutral.
 */
export const NOTIFIER_PROGRAM_NAME = "roubo-notify";

/** Where the program is installed. Prepended to the agent's PATH at launch. */
export function getNotifierDir(): string {
  return path.join(getRouboDir(), "bin");
}

/** The absolute path the `{{notifier}}` placeholder resolves to. */
export function getNotifierPath(): string {
  return path.join(getNotifierDir(), NOTIFIER_PROGRAM_NAME);
}

function notifierEndpoint(port: string): string {
  return `http://localhost:${port}/api/hooks/agent-notification`;
}

/**
 * The script body, with `endpoint` already resolved.
 *
 * Argv contract: the correlation token is the FIRST argument (the last element
 * of the carrier argv the plugin declared) and the event JSON is the LAST
 * argument (the one the agent appends). The canonical invocation carries
 * exactly those two, so both readings agree.
 *
 * The payload is forwarded as a JSON string rather than as raw JSON, so a
 * payload the agent did not format as an object still produces a well-formed
 * request body instead of a 400 that silently loses the notification.
 */
export function buildNotifierScript(endpoint: string): string {
  return `#!/bin/sh
# Generated by Roubo. Do not edit: this file is rewritten on every agent launch.
#
# Correlation notifier for the spawned-notifier notification wiring. An agent
# spawns it when its declared event fires, with the resolved correlation token
# first and the event JSON appended last; it forwards both to Roubo, which
# trades the token for the session that owns it.
#
# The endpoint is baked in because Roubo strips its own port from every bench
# child environment, so there is nothing to read at runtime.
set -eu

ENDPOINT='${endpoint}'

if [ "$#" -lt 2 ]; then
  echo 'roubo-notify: expected <correlation-token> [args...] <event-json>' >&2
  exit 2
fi

token=$1
payload=$1
for arg in "$@"; do
  payload=$arg
done

# Escape a value for embedding in a JSON string: backslashes and double quotes
# first, then real newlines into their two-character escape, then any remaining
# control characters dropped so the body always parses.
json_string() {
  printf '%s' "$1" |
    sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g' -e '$!s/$/\\\\n/' |
    tr -d '\\000-\\037'
}

body='{"token":"'$(json_string "$token")'","payload":"'$(json_string "$payload")'"}'

# Never fail the agent's turn: a Roubo that is not listening, or a curl that is
# not installed, costs a notification and nothing more.
command -v curl >/dev/null 2>&1 || exit 0
curl -sS -m 5 -X POST -H 'Content-Type: application/json' \\
  --data-binary "$body" "$ENDPOINT" >/dev/null 2>&1 || exit 0
`;
}

/**
 * Write the notifier program for the given port and return its absolute path.
 *
 * Rewritten on every call rather than written once, so a server that came back
 * up on a different port is picked up by the next launch instead of leaving
 * sessions pointing at a dead endpoint. The path is fixed, so nothing a plugin
 * declares reaches the filesystem here.
 */
export function ensureNotifierInstalled(port: string): string {
  const dir = getNotifierDir();
  const filePath = path.join(dir, NOTIFIER_PROGRAM_NAME);
  fs.mkdirSync(dir, { recursive: true });
  atomicWrite(filePath, buildNotifierScript(notifierEndpoint(port)), 0o755);
  return filePath;
}
