import fs from "node:fs";
import path from "node:path";
import { atomicWrite, getRouboDir } from "./state.js";

/**
 * The notifier program core ships for the `spawned-notifier` notification
 * wiring (#1113, AP-FR-013).
 *
 * An agent declaring `capabilities.notification.kind === "spawned-notifier"`
 * cannot POST to core itself: it spawns a configured program when its declared
 * event fires, passing that program's configured arguments plus the event JSON
 * as one final argument. Core therefore has to supply the program, and the
 * program has to be agent-generic: nothing here knows or cares which agent
 * spawned it, so the name carries no agent vocabulary.
 *
 * Two constraints shape it.
 *
 * The `file-notifier` wiring (#1265) runs the same program
 * through a shell with the token as its only argument and the event JSON on
 * standard input; see `buildNotifierScript` for how it tells the two apart.
 *
 * The endpoint URL is baked in at write time rather than read from the
 * environment, because ROUBO_PORT is deliberately stripped from every bench
 * child env (HOST_INTERNAL_ENV_KEYS in terminal.ts): core tells the agent the
 * port, the agent never inherits it. The notifier is a child of the agent, so it
 * inherits the same stripped env and has no runtime way to learn the port. The
 * same reasoning already bakes the hook URL into the Claude Code settings write.
 *
 * It is a POSIX `sh` script rather than a Node entry point, because the packaged
 * app targets macOS and Linux only and a Node program would have to be a second
 * bundle output beside the single-entry server bundle. `sh` plus `curl` is
 * present on both targets and starts in milliseconds.
 */

/**
 * The program name a plugin writes into its carrier argv. Fixed, never
 * interpolated from plugin input, and deliberately agent-neutral.
 */
export const NOTIFIER_PROGRAM_NAME = "roubo-notify";

/** Where the program is installed. Prepended to the agent's PATH at launch. */
export function getNotifierDir(): string {
  return path.join(getRouboDir(), "bin");
}

/** The absolute path the `{{notifier}}` placeholder resolves to. */
export function getNotifierPath(): string {
  return path.join(getNotifierDir(), NOTIFIER_PROGRAM_NAME);
}

function notifierEndpoint(port: string): string {
  return `http://localhost:${port}/api/hooks/agent-notification`;
}

/**
 * The script body, with `endpoint` already resolved.
 *
 * Argv contract: the correlation token is always the FIRST argument (the last
 * element of the carrier argv the plugin declared). Where the event JSON comes
 * from is selected by argument count alone, never by testing whether a stream
 * is a terminal:
 *
 * - two or more arguments: the event JSON is the LAST argument (the one a
 *   `spawned-notifier` agent appends). The canonical invocation carries exactly
 *   those two, so both readings agree.
 * - exactly one argument: the event JSON is read from standard input (what a
 *   `file-notifier` agent writes, #1265). The read is
 *   bounded by the same five-second window as the request, so a caller that
 *   holds stdin open without sending end of file cannot hang the program, and
 *   the reader is killed and reaped before the request so no child outlives it.
 * - no arguments: a usage error, exit 2.
 *
 * Both sources then build the same body and post it to the same endpoint.
 *
 * The payload is forwarded as a JSON string rather than as raw JSON, so a
 * payload the agent did not format as an object still produces a well-formed
 * request body instead of a 400 that silently loses the notification.
 */
export function buildNotifierScript(endpoint: string): string {
  return `#!/bin/sh
# Generated by Roubo. Do not edit: this file is rewritten on every agent launch.
#
# Correlation notifier for the spawned-notifier and file-notifier notification
# wirings. An agent runs it when its declared event fires, with the resolved
# correlation token first. The event JSON is the last argument when there are
# two or more, and standard input when the token is the only one. It forwards
# both to Roubo, which trades the token for the session that owns it.
#
# The endpoint is baked in because Roubo strips its own port from every bench
# child environment, so there is nothing to read at runtime.
set -eu

ENDPOINT='${endpoint}'

if [ "$#" -eq 0 ]; then
  echo 'roubo-notify: expected <correlation-token> [[args...] <event-json>]' >&2
  exit 2
fi

token=$1

if [ "$#" -eq 1 ]; then
  # The event JSON arrives on standard input. The path is chosen by argument
  # count alone, never by testing whether stdin is a terminal.
  #
  # The read is bounded by the same window as the request below: a background
  # reader drains stdin into a temp file while this shell polls it, and a
  # reader still running at the deadline is killed. Either way it is reaped
  # before anything else runs, so no child outlives the program. A background
  # command's stdin is /dev/null unless redirected, so stdin is handed to it on
  # descriptor 3.
  tmp=$(mktemp "\${TMPDIR:-/tmp}/roubo-notify.XXXXXX") || exit 0
  trap 'rm -f "$tmp"' EXIT
  exec 3<&0
  cat <&3 >"$tmp" 2>/dev/null &
  reader=$!
  exec 3<&-
  deadline=$(( $(date +%s) + 5 ))
  while kill -0 "$reader" 2>/dev/null; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      kill "$reader" 2>/dev/null || :
      break
    fi
    sleep 0.1 2>/dev/null || sleep 1
  done
  wait "$reader" 2>/dev/null || :
  payload=$(cat "$tmp")
else
  payload=$1
  for arg in "$@"; do
    payload=$arg
  done
fi

# Escape a value for embedding in a JSON string: backslashes and double quotes
# first, then real newlines into their two-character escape, then any remaining
# control characters dropped so the body always parses.
json_string() {
  printf '%s' "$1" |
    sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g' -e '$!s/$/\\\\n/' |
    tr -d '\\000-\\037'
}

body='{"token":"'$(json_string "$token")'","payload":"'$(json_string "$payload")'"}'

# Never fail the agent's turn: a Roubo that is not listening, or a curl that is
# not installed, costs a notification and nothing more.
command -v curl >/dev/null 2>&1 || exit 0
curl -sS -m 5 -X POST -H 'Content-Type: application/json' \\
  --data-binary "$body" "$ENDPOINT" >/dev/null 2>&1 || exit 0
`;
}

/**
 * Write the notifier program for the given port and return its absolute path.
 *
 * Rewritten on every call rather than written once, so a server that came back
 * up on a different port is picked up by the next launch instead of leaving
 * sessions pointing at a dead endpoint. The path is fixed, so nothing a plugin
 * declares reaches the filesystem here.
 */
export function ensureNotifierInstalled(port: string): string {
  const dir = getNotifierDir();
  const filePath = path.join(dir, NOTIFIER_PROGRAM_NAME);
  fs.mkdirSync(dir, { recursive: true });
  atomicWrite(filePath, buildNotifierScript(notifierEndpoint(port)), 0o755);
  return filePath;
}
